### ISSUE TITLE
Using Threading with pronouncing.rhymes returns inaccurate candidates

### ISSUE THREAD

**Issue by WillPiledriver** [aparrish/pronouncingpy#28]
I'm making a [little project](https://github.com/WillPiledriver/rapgod) for fun that takes a huge amount of text data and tries to make a song. I tried to speed the process of finding rhyme candidates by using threading.

```
def addCandidates(strings, index):
    lastWord = ''.join(filter(str.isalpha, strings[index]["string"].strip().split(" ")[-1])).lower()
    strings[index]["candidates"] = pronouncing.rhymes(lastWord)
    strings[index]["lastWord"] = lastWord


...
...
...

    # Start a new thread for each string to find out all the rhyme candidates
    # Maximum thread pool for this process is 25 threads.
    x = 0
    while activeCount() < 25:

        process = Thread(target=addCandidates, args=[strings, x])
        process.start()
        threads.append(process)
        if x % 100 == 0:
            times[1] = time()
            print("{}% complete // {} sentences // {} threads // {} seconds // {} per second".format(int(x / len(strings) * 100), x, activeCount(), int(times[1]-times[0]), x / (times[1] + 0.00001 - times[0])))
        if x == len(strings):
            break
        x += 1


    # Wait for threads to finish processing
    for process in threads:
        process.join()
```

I figured by doing Threading, it would complete a lot faster. But it turns out threading slows down the process by 5-10% while also returning incorrect data.

For example, some of the threads will return a blank list for the word 'of' while others will return the correct candidates for the same word. I thought I was doing something wrong, but when i removed the threading, rhymes() was 100% accurate.

Any explanation for this? I would like to speed up the process somehow because currently the processing time is about 4-7 words per second which is incredibly slow when dealing with thousands of words.

**Comment by aparrish** [comment]
Hmm, okay, I think I see the problem. The only part of the library that isn't thread safe is loading the data from disk. For convenience, by default, the data is first loaded not on import but *only when you call any function in the library that requires it*. This means that there's a potential race condition if the first time you call a function in the library occurs in a thread. Try adding this line in the synchronous part of your program, before you start any of the threading code:

    pronouncing.init_cmu()

This will load the data into the module's global variable. Once it's there, subsequent calls won't attempt to load the data, thereby avoiding the race condition.

That doesn't solve the underlying speed problem, though. The `rhyme()` function checks each item in the CMU data for a match, which means that every call sets off 100k+ checks. If I'm understanding your scenario correctly, I'd advise creating a dictionary whose keys are the "rhyming part" of each word in the CMU data, and whose values are the words that share that rhyming part. (You can use the `rhyming_part()` function in the library for this.) E.g., the data structure would end up looking like:

    {'IY1 Z IY0': [u'adelizzi', u'breezy', u'caseze', u'cheesy', u'easy', u'fabrizi', u'kasese', u'marchese', u'matterease', u'mcaleese', u'peasey', u'queasy', u'scortese', u'sleazy', u'sweazy', u'sweezey', u'sweezy', u'talese', u'uneasy', u'veasey', u'veazey', u'veazie'], ...}

That way, finding rhyming words is O(1) instead of O(n). You can then use `rhyming_part()` on each of the lines in your source text, and look them up in the dictionary using the rhyming part as the key.

**Comment by WillPiledriver** [comment]
Thanks, a lot @aparrish . I did as you suggested.

```def init_cmu(filehandle=None):
    """Initialize the module's pronunciation data.

    This function is called automatically the first time you attempt to use
    another function in the library that requires loading the pronunciation
    data from disk. You can call this function manually to control when and
    how the pronunciation data is loaded (e.g., you're using this module in
    a web application and want to load the data asynchronously).

    :param filehandle: a filehandle with CMUdict-formatted data
    :returns: None
    """
    global pronunciations, lookup, rhymeDict
    if pronunciations is None:
        if filehandle is None:
            filehandle = resource_stream(__name__, 'cmudict-0.7b')
        pronunciations = parse_cmu(filehandle)
        filehandle.close()
        lookup = collections.defaultdict(list)
        for word, phones in pronunciations:
            lookup[word].append(phones)

        rhymeDict = collections.defaultdict(list)
        for word, phones in pronunciations:
            rp = rhyming_part(phones)
            if rp is not None:
                rhymeDict[rhyming_part(phones)].append(word)

def rhymesFast(word):
    phones = phones_for_word(word)
    if not phones == []:
        rd = rhymeDict[rhyming_part(phones[0])]
        if word in rd:
            rd.pop(rd.index(word))
        return rd
    else:
        return []
```

after tweaking the code, I was able to find rhyme candidates for 4200 words in 1 second.
