### ISSUE TITLE
LRU cache for phones_for_word lookups

### ISSUE THREAD

**Issue by aparrish** [aparrish/pronouncingpy#8]
I'm actually using the library for a thing right now and the performance isn't quite where I want it to be. I'd like to investigate drop-in LRU cache implementations and see if I can add one to at least the `phones_for_word` call in order to improve performance a little bit without needing to make a big dictionary for word-to-phone lookups. Starting point [here](http://stackoverflow.com/questions/11815873/memoization-library-for-python-2-7)

**Comment by mewo2** [comment]
I ran into some similar problems, so I rejigged things to use a dict internally (#10). The speed-up on `phones_for_word` is of the order of 30000x. Not sure if you want something smarter.

**Comment by aparrish** [comment]
See #10—I really would prefer something that doesn't use a dictionary for the internal representation. It's faster for lookups, but I'm personally more concerned in the long run about the performance of `search()` and keeping the library as lean memory-wise as possible. Off the top of my head, solutions I'd consider merging include a LRU as described above, or a function that returns a dictionary that can be used for quick lookups (at the discretion of the user).

**Comment by mewo2** [comment]
The problem I ran into was that I had no idea that `phones_for_word` was as inefficient as it is. I was working with it for several days before I thought to look at how it's implemented. I imagine a less technically proficient user might never think to look.

If you weren't focused on memory usage, my suggestion would be to look at different internal representations for each of the functions. The speed-up which is possible on `phones_for_word` (and related functions) is really quite substantial. The only way I can think to speed up `search` is to run a regex over the full dictionary, rather than individually on each line.

**Comment by aparrish** [comment]
That's a good point, I'll consider adding an FAQ item.

**Comment by aparrish** [comment]
just went ahead and added a dictionary lookup (#22). thanks everyone for coping with me being obstinate 👍
